services:
  feline:
    image: node:18-alpine
    command: sh -c "npm install && npm run build"
    ports:
      - 80:9000
    working_dir: /feline
    volumes:
      - ./:/feline
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: hg178ar6
      MYSQL_DB: feline
  mysql:
    image: mysql:8.0
    volumes:
      - feline-mysql-date:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: hg178ar6
      MYSQL_DATABASE: feline

volumes:
  feline-mysql-data:
